baseURL = 'https://maxcohen31.github.io/'
languageCode = 'en-us'
title = "Max's digital space"
metaDataFormat = "yaml"
theme = "m10c"


[params]
 author = "Emanuele Abbate"
 description = "Aspiring data scientist. Lost in the digital world."
 avatar = "Downloads/retro.jpg"
 


 [[params.social]]
  icon = "github"
  name = "Github"
  url = "https://github.com/maxcohen31"