baseURL = 'https://maxcohen31.github.io/'
languageCode = 'en-us'
title = "Max's blog"
metaDataFormat = "yaml"
theme = "m10c"
disableKinds = ['taxonomy']

[params]
 author = "Emanuele Abbate"
 menu_item_separator = " | "
 description = "CS student | GNU/Linux enthusiast | Aspiring Data scientist"
 avatar = "img/picme.jpg"

[[menu.main]]
    name = "Home"
    url = "/"

[[menu.main]]
    name = "About"
    url = "/about/"

 [[params.social]]
  icon = "github"
  name = "Github"
  url = "https://github.com/maxcohen31"
